"""feat: default values for created_by and modified_by

Revision ID: 5aad35d5d963
Revises: 7f12a8775fd6
Create Date: 2023-02-12 18:12:41.335759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aad35d5d963'
down_revision = '7f12a8775fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
