"""fix: foreign key names

Revision ID: 5efa0aaf3a49
Revises: 9e0115c3561b
Create Date: 2023-02-11 18:50:51.899780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efa0aaf3a49'
down_revision = '9e0115c3561b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
