"""fix: typo (modifed -> modified)

Revision ID: 7f12a8775fd6
Revises: 5efa0aaf3a49
Create Date: 2023-02-11 19:06:40.634470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f12a8775fd6'
down_revision = '5efa0aaf3a49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('operations', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.drop_index('ix_operations_modifed_by', table_name='operations')
    op.create_index(op.f('ix_operations_modified_by'), 'operations', ['modified_by'], unique=False)
    op.drop_constraint('operations_modifed_by_fkey', 'operations', type_='foreignkey')
    op.create_foreign_key('updated_by_fk', 'operations', 'users', ['modified_by'], ['id'])
    op.drop_column('operations', 'modifed_by')
    op.drop_column('operations', 'modifed_at')
    op.add_column('products', sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('products', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.drop_index('ix_products_modifed_by', table_name='products')
    op.create_index(op.f('ix_products_modified_by'), 'products', ['modified_by'], unique=False)
    op.drop_constraint('products_modifed_by_fkey', 'products', type_='foreignkey')
    op.create_foreign_key('updated_by_fk', 'products', 'users', ['modified_by'], ['id'])
    op.drop_column('products', 'modifed_by')
    op.drop_column('products', 'modifed_at')
    op.add_column('tanks', sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('tanks', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.drop_index('ix_tanks_modifed_by', table_name='tanks')
    op.create_index(op.f('ix_tanks_modified_by'), 'tanks', ['modified_by'], unique=False)
    op.drop_constraint('tanks_modifed_by_fkey', 'tanks', type_='foreignkey')
    op.create_foreign_key('updated_by_fk', 'tanks', 'users', ['modified_by'], ['id'])
    op.drop_column('tanks', 'modifed_by')
    op.drop_column('tanks', 'modifed_at')
    op.add_column('users', sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.drop_index('ix_users_modifed_by', table_name='users')
    op.create_index(op.f('ix_users_modified_by'), 'users', ['modified_by'], unique=False)
    op.drop_constraint('users_modifed_by_fkey', 'users', type_='foreignkey')
    op.create_foreign_key('updated_by_fk', 'users', 'users', ['modified_by'], ['id'])
    op.drop_column('users', 'modifed_by')
    op.drop_column('users', 'modifed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('modifed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('modifed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('updated_by_fk', 'users', type_='foreignkey')
    op.create_foreign_key('users_modifed_by_fkey', 'users', 'users', ['modifed_by'], ['id'])
    op.drop_index(op.f('ix_users_modified_by'), table_name='users')
    op.create_index('ix_users_modifed_by', 'users', ['modifed_by'], unique=False)
    op.drop_column('users', 'modified_by')
    op.drop_column('users', 'modified_at')
    op.add_column('tanks', sa.Column('modifed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tanks', sa.Column('modifed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('updated_by_fk', 'tanks', type_='foreignkey')
    op.create_foreign_key('tanks_modifed_by_fkey', 'tanks', 'users', ['modifed_by'], ['id'])
    op.drop_index(op.f('ix_tanks_modified_by'), table_name='tanks')
    op.create_index('ix_tanks_modifed_by', 'tanks', ['modifed_by'], unique=False)
    op.drop_column('tanks', 'modified_by')
    op.drop_column('tanks', 'modified_at')
    op.add_column('products', sa.Column('modifed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('modifed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('updated_by_fk', 'products', type_='foreignkey')
    op.create_foreign_key('products_modifed_by_fkey', 'products', 'users', ['modifed_by'], ['id'])
    op.drop_index(op.f('ix_products_modified_by'), table_name='products')
    op.create_index('ix_products_modifed_by', 'products', ['modifed_by'], unique=False)
    op.drop_column('products', 'modified_by')
    op.drop_column('products', 'modified_at')
    op.add_column('operations', sa.Column('modifed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('operations', sa.Column('modifed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('updated_by_fk', 'operations', type_='foreignkey')
    op.create_foreign_key('operations_modifed_by_fkey', 'operations', 'users', ['modifed_by'], ['id'])
    op.drop_index(op.f('ix_operations_modified_by'), table_name='operations')
    op.create_index('ix_operations_modifed_by', 'operations', ['modifed_by'], unique=False)
    op.drop_column('operations', 'modified_by')
    op.drop_column('operations', 'modified_at')
    # ### end Alembic commands ###
