"""fix: replace onupdate value for modified_at column for all entities

Revision ID: 991a1260c1ad
Revises: abd53c807df4
Create Date: 2023-02-13 15:00:53.252569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991a1260c1ad'
down_revision = 'abd53c807df4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
