"""Init revision

Revision ID: 9e0115c3561b
Revises: 
Create Date: 2023-02-11 17:33:09.146991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0115c3561b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('password_hashed', sa.String(), nullable=True),
                    sa.Column('role', sa.Enum('admin', 'viewer',
                                              name='ct_roles'), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modifed_at', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('modifed_by', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['modifed_by'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_created_by'), 'users',
                    ['created_by'], unique=False)
    op.create_index(op.f('ix_users_modifed_by'), 'users',
                    ['modifed_by'], unique=False)
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modifed_at', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('modifed_by', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['modifed_by'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_products_created_by'),
                    'products', ['created_by'], unique=False)
    op.create_index(op.f('ix_products_modifed_by'),
                    'products', ['modifed_by'], unique=False)
    op.create_table('tanks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('max_capacity', sa.Float(), nullable=True),
                    sa.Column('current_capacity', sa.Float(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modifed_at', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('modifed_by', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['modifed_by'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tanks_created_by'), 'tanks',
                    ['created_by'], unique=False)
    op.create_index(op.f('ix_tanks_modifed_by'), 'tanks',
                    ['modifed_by'], unique=False)
    op.create_table('operations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('mass', sa.Float(), nullable=True),
                    sa.Column('date_start', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('date_end', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('tank_id', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modifed_at', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('modifed_by', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['modifed_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_operations_created_by'),
                    'operations', ['created_by'], unique=False)
    op.create_index(op.f('ix_operations_modifed_by'),
                    'operations', ['modifed_by'], unique=False)
    op.create_index(op.f('ix_operations_product_id'),
                    'operations', ['product_id'], unique=False)
    op.create_index(op.f('ix_operations_tank_id'),
                    'operations', ['tank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_tank_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_product_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_modifed_by'), table_name='operations')
    op.drop_index(op.f('ix_operations_created_by'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_tanks_modifed_by'), table_name='tanks')
    op.drop_index(op.f('ix_tanks_created_by'), table_name='tanks')
    op.drop_table('tanks')
    op.drop_index(op.f('ix_products_modifed_by'), table_name='products')
    op.drop_index(op.f('ix_products_created_by'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_modifed_by'), table_name='users')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
