"""fix: missing constraint

Revision ID: b0e46ec1adbf
Revises: d25fe29f6d45
Create Date: 2023-02-13 22:07:19.760804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e46ec1adbf'
down_revision = 'd25fe29f6d45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
