"""fix: missing foreign key on product for tank

Revision ID: d25fe29f6d45
Revises: 991a1260c1ad
Create Date: 2023-02-13 17:00:49.090243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25fe29f6d45'
down_revision = '991a1260c1ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('created_by_fk', 'tanks', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('created_by_fk', 'tanks', type_='foreignkey')
    # ### end Alembic commands ###
